### ISSUE TITLE
Action does not support users.list() pagination

### ISSUE THREAD

**Issue by julioz** [camisinc/action-slack-user#17]
The Slack [`users.list()` API](https://api.slack.com/methods/users.list) returns a list of [paginated](https://api.slack.com/docs/pagination) [user objects](https://api.slack.com/types/user), in no particular order.

This action is only searching for users in the first returned page, but fails to find a user if it is present in a following page from the users' list.

**Comment by julioz** [comment]
One alternative to going through the entire list is to use [users.lookupByEmail](https://api.slack.com/methods/users.lookupByEmail) instead. Have you considered that?

**Comment by alec-malcolm** [comment]
This was likely just an oversight on my part, and since we have a small organization it's never been an issue. I will try and make some time to address this soon. Thanks for bringing the issue to my attention!

**Comment by alec-malcolm** [comment]
This should be fixed in https://github.com/camisinc/action-slack-user/pull/18
