### ISSUE TITLE
What is the bot token scope needed?

### ISSUE THREAD

**Issue by IvanNoronha-TomTom** [camisinc/action-slack-user#6]
My current slack app has the following permission
![image](https://user-images.githubusercontent.com/73875852/171145591-8517025a-0c63-415f-b8a8-341745bfb6c6.png)

When I try to run `action-slack-user` I get
```
Error: Failed to set email for github user User1
```

So perhaps my bot is missing some scope possibly the read one?
![image](https://user-images.githubusercontent.com/73875852/171146339-b7058c03-9027-4b42-8ddc-961dee5e5d56.png)

**Comment by IvanNoronha-TomTom** [comment]
I added both scopes and atleast via curl I'm able to verify that user info can be retrieved with email
```
curl -X POST -H "Authorization: Bearer xoxb-abcd" -F 'email=myemail@company.com' https://slack.com/api/users.lookupByEmail | jq -r '. | select(.ok) | .user.id'

```

But the github action still gives same error

**Comment by alec-malcolm** [comment]
Sorry for the late reply @IvanNoronha-TomTom but you'll need to have your email publicly visible on GitHub for this to work properl
![Capture](https://user-images.githubusercontent.com/84037272/176260749-7209aeac-ca0c-41f8-95ba-8051a5890197.PNG)
y

**Comment by IvanNoronha-TomTom** [comment]
Interesting. I can't see that option. Maybe it's an org level restriction I'll need to check,
![image](https://user-images.githubusercontent.com/73875852/176261781-652a4e4d-5cad-4c70-ab22-7eb9c63379fd.png)
